---
- name: Install nginx
  apt:
    name:
    - nginx
    - apache2-utils
    state: latest
    update_cache: yes

- name: Copy configuration
  template:
    src: wamf.conf.j2
    dest: /etc/nginx/sites-available/wamf.conf

- name: Enable site
  file:
    src: /etc/nginx/sites-available/wamf.conf
    dest: /etc/nginx/sites-enabled/wamf.conf
    state: link

# TODO: Generate htpasswd on the fly
# - name: Add a user to a password file and ensure permissions are set
#   command:
