---
# tasks file for caddy
- name: Install caddy dependencies
  apt:
    name: 
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    state: latest
    update_cache: yes

- shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
#
- shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list

- name: Install caddy
  apt:
    name: caddy
    state: latest
    update_cache: yes
