services:
  backend:
    image: "ghcr.io/wheremyfriends/webapp:main"
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:$POSTGRES_PORT/$POSTGRES_DB
    ports:
      - 127.0.0.1:4000:4000
  db:
    image: "postgres:16.3-alpine3.20"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT

volumes:
  pgdata:
