---
# Dependencies
# Client
# Server
# Webhook
# Caddy
- name: Log into docker
  become_user: "{{ansible_user}}"
  shell: echo "{{ GHCR_API_KEY }}" | docker login --username "{{GHCR_USER}}" --password-stdin ghcr.io

- name: Make directories
  file:
    path: "{{item}}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - "{{working_directory}}"

- name: Include caddy.yml
  include_tasks: ./caddy.yml

- name: Include webhook.yml
  include_tasks: ./webhook.yml

- name: Include server.yml
  include_tasks: ./server.yml

- name: Include client.yml
  include_tasks: ./client.yml

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start webhook service
  ansible.builtin.systemd_service:
    name: wamf-webhook.service
    enabled: true
    state: started
