- name: Copy env file for server
  template:
    src: env.server.j2
    dest: "{{ working_directory }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Copy compose.yaml
  copy:
    src: compose.yaml
    dest: "{{ working_directory }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'


- name: Start containers
  become_user: "{{ansible_user}}"
  command:
    cmd: docker compose up -d
    chdir: "{{ working_directory }}"
