---
- name: Copy webhook files
  copy:
    src: "{{item}}"
    dest: "{{ working_directory }}"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  loop:
    - ./webhook
    - poetry.lock
    - pyproject.toml

- name: Install wamf-webhook.service
  ansible.builtin.template:
    src: wamf-webhook.service.j2
    dest: /etc/systemd/system/wamf-webhook.service
    owner: root
    group: root
    mode: '0644'

- name: Copy env file
  template:
    src: env.client.j2
    dest: "{{ working_directory }}/.env.client"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'


- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start webhook service
  ansible.builtin.systemd_service:
    name: wamf-webhook.service
    enabled: true
    state: started
